EXTERNAL playEmote(emoteName)
EXTERNAL showTaskPanel()
EXTERNAL rewardItem(itemCode, quantity)
EXTERNAL rewardWeapon(weaponCode, level)
EXTERNAL switch2NextTask()
EXTERNAL doneCriteriaTask(criteria)
EXTERNAL guide()