public enum CharacterCode
{
    NoActor = 0,
    AuCo = 1,
    Doi = 2,
    Gam = 3,
    King = 4,
    LacLongQuan = 5,
    Lua = 6,
    MissCam = 7,
    MissTam = 8,
    MrsKim = 9,
    MrTinh = 10,
    MrVe = 11,
    RichMan = 12,
    SonTinh = 13,
    Tam = 14,
    Teo = 15,
    ThuyTinh = 16,
    VillageElder = 17,
    MorthersTam = 18,
}
